spring:
  application:
    name: Catalog
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
