server:
  port: ${PORT_CONFIG_SERVER:8888}
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Brenex000006/CloudConfig-Chackepoin-1.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true

